DDL TRIGGER ON DATABASE

CREATE TABLESPACE RECAUDADOR_AUDIT DATAFILE '/u02/oradata/rec01/recaudador_audit_01.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;

CREATE TEMPORARY TABLESPACE RECAUDADOR_AUDIT_TEMP TEMPFILE '/u02/oradata/rec01/recaudador_audit_temp_01.dbf' SIZE 50M AUTOEXTEND ON NEXT 50M MAXSIZE UNLIMITED;

CREATE USER RECAUDADOR_AUDIT IDENTIFIED BY R34$#01sd0T profile RECPROFILE default TABLESPACE RECAUDADOR_AUDIT TEMPORARY TABLESPACE RECAUDADOR_AUDIT_TEMP ACCOUNT UNLOCK;

GRANT CONNECT, RESOURCE TO RECAUDADOR_AUDIT;

GRANT SELECT ON V_$SESSION TO RECAUDADOR_AUDIT;

GRANT UNLIMITED TABLESPACE TO RECAUDADOR_AUDIT;


CREATE TABLE ddl_log (
user_name     VARCHAR2(30),
ddl_date      DATE,
ddl_type      VARCHAR2(30),
object_type   VARCHAR2(18),
owner         VARCHAR2(30),
object_name   VARCHAR2(128),
OSUSER VARCHAR2(255),
CURRENT_USER VARCHAR2(255),
HOST VARCHAR2(255),
TERMINAL VARCHAR2(255));

CREATE OR REPLACE TRIGGER ddl_trig
AFTER DDL
ON DATABASE

BEGIN
  INSERT INTO RECAUDADOR_AUDIT.ddl_log
  (user_name, ddl_date, ddl_type,
   object_type, owner,
   object_name,OSUSER,CURRENT_USER,HOST)
  VALUES
  (ora_login_user, SYSDATE, ora_sysevent,
   ora_dict_obj_type, ora_dict_obj_owner,
   ora_dict_obj_name,
   SYS_CONTEXT('USERENV','OS_USER'),
   SYS_CONTEXT('USERENV','CURRENT_USER'),
   SYS_CONTEXT('USERENV','HOST'));
END ddl_trig;
/