CREATE SMALLFILE TABLESPACE "REC_CAJAS" DATAFILE '/u02/oradata/rec/rec_cajas_01.dbf' SIZE 200M REUSE AUTOEXTEND ON NEXT 4096K MAXSIZE 32767M LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE SMALLFILE TABLESPACE "REC_CAJAS_IND" DATAFILE '/u02/oradata/rec/rec_cajas_ind_01.dbf' SIZE 200M REUSE AUTOEXTEND ON NEXT 4096K MAXSIZE 32767M LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE SMALLFILE TABLESPACE "REC_CARGAS" DATAFILE '/u02/oradata/rec/rec_cargas_01.dbf' SIZE 200M REUSE AUTOEXTEND ON NEXT 4096K MAXSIZE 32767M LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE SMALLFILE TABLESPACE "REC_CARGAS_IND" DATAFILE '/u02/oradata/rec/rec_cargas_ind_01.dbf' SIZE 200M REUSE AUTOEXTEND ON NEXT 4096K MAXSIZE 32767M LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE SMALLFILE TABLESPACE "REC_CATALOGOS" DATAFILE '/u02/oradata/rec/rec_catalogos_01.dbf' SIZE 200M REUSE AUTOEXTEND ON NEXT 4096K MAXSIZE 32767M LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE SMALLFILE TABLESPACE "REC_CATALOGOS_IND" DATAFILE '/u02/oradata/rec/rec_catalogos_ind_01.dbf' SIZE 200M REUSE AUTOEXTEND ON NEXT 4096K MAXSIZE 32767M LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE SMALLFILE TABLESPACE "REC_PADRON" DATAFILE '/u02/oradata/rec/rec_padron_01.dbf' SIZE 200M REUSE AUTOEXTEND ON NEXT 4096K MAXSIZE 32767M LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE SMALLFILE TABLESPACE "REC_PADRON_IND" DATAFILE '/u02/oradata/rec/rec_padron_ind_01.dbf' SIZE 200M REUSE AUTOEXTEND ON NEXT 4096K MAXSIZE 32767M LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE SMALLFILE TABLESPACE "REC_FACTURACION" DATAFILE '/u02/oradata/rec/rec_facturacion_01.dbf' SIZE 209715200 AUTOEXTEND ON NEXT 4194304 MAXSIZE 34358689792 BLOCKSIZE 8192 DEFAULT NOCOMPRESS NO INMEMORY ONLINE SEGMENT SPACE MANAGEMENT AUTO EXTENT MANAGEMENT LOCAL AUTOALLOCATE;
CREATE SMALLFILE TABLESPACE "REC_FACTURACION_IND" DATAFILE '/u02/oradata/rec/rec_facturacion_ind_01.dbf' SIZE 209715200 AUTOEXTEND ON NEXT 4194304 MAXSIZE 34358689792 BLOCKSIZE 8192 DEFAULT NOCOMPRESS NO INMEMORY ONLINE SEGMENT SPACE MANAGEMENT AUTO EXTENT MANAGEMENT LOCAL AUTOALLOCATE;


CREATE PROFILE "RECPROFILE" LIMIT CPU_PER_SESSION UNLIMITED
CPU_PER_CALL UNLIMITED
CONNECT_TIME UNLIMITED
IDLE_TIME UNLIMITED
SESSIONS_PER_USER UNLIMITED
LOGICAL_READS_PER_SESSION UNLIMITED
LOGICAL_READS_PER_CALL UNLIMITED
PRIVATE_SGA UNLIMITED
COMPOSITE_LIMIT UNLIMITED
PASSWORD_LIFE_TIME UNLIMITED
PASSWORD_GRACE_TIME 7
PASSWORD_REUSE_MAX UNLIMITED
PASSWORD_REUSE_TIME UNLIMITED
PASSWORD_LOCK_TIME 1
FAILED_LOGIN_ATTEMPTS UNLIMITED
PASSWORD_VERIFY_FUNCTION NULL

CREATE USER "RECAINT" PROFILE "RECPROFILE" IDENTIFIED BY recaint DEFAULT TABLESPACE "REC_PADRON" TEMPORARY TABLESPACE "TEMP" ACCOUNT UNLOCK;
GRANT CREATE DATABASE LINK TO "RECAINT";
GRANT CREATE VIEW TO "RECAINT";
GRANT UNLIMITED TABLESPACE TO "RECAINT";
GRANT "CONNECT" TO "RECAINT";
GRANT "RESOURCE" TO "RECAINT";


